/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.46                          *
*        Compiled Dec 12 2017, 16:38:40                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "../../util.h"
// USER END

#include "DIALOG.h"
extern State state;
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0            (GUI_ID_USER + 0x00)
#define ID_TEXT_0            (GUI_ID_USER + 0x01)
#define ID_TEXT_1            (GUI_ID_USER + 0x02)
#define ID_SLIDER_0            (GUI_ID_USER + 0x03)
#define ID_TEXT_2            (GUI_ID_USER + 0x04)
#define ID_TEXT_3            (GUI_ID_USER + 0x05)
#define ID_RADIO_0            (GUI_ID_USER + 0x06)
#define ID_TEXT_4            (GUI_ID_USER + 0x07)
#define ID_TEXT_5            (GUI_ID_USER + 0x08)
#define ID_BUTTON_0            (GUI_ID_USER + 0x09)
#define ID_BUTTON_1            (GUI_ID_USER + 0x0A)
#define ID_TEXT_6            (GUI_ID_USER + 0x0B)
#define ID_TEXT_7            (GUI_ID_USER + 0x0C)
#define ID_TEXT_8            (GUI_ID_USER + 0x0D)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "Temperatuur", ID_FRAMEWIN_0, -1, -1, 240, 320, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Temperature:", ID_TEXT_0, 8, 11, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "temperature_value", ID_TEXT_1, 98, 8, 80, 20, 0, 0x64, 0 },
  { SLIDER_CreateIndirect, "Slider", ID_SLIDER_0, 9, 116, 211, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "slider_value", ID_TEXT_2, 78, 87, 118, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Desired Temperature:", ID_TEXT_3, 51, 64, 123, 20, 0, 0x0, 0 },
  { RADIO_CreateIndirect, "Radio", ID_RADIO_0, 141, 165, 71, 44, 0, 0x1402, 0 },
  { TEXT_CreateIndirect, "Fan:", ID_TEXT_4, 8, 28, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "fan_state", ID_TEXT_5, 98, 27, 80, 20, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "Fan On", ID_BUTTON_0, 12, 240, 80, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Fan Off", ID_BUTTON_1, 122, 240, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "info_message", ID_TEXT_6, 7, 272, 218, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Current Fanmode:", ID_TEXT_7, 7, 163, 118, 23, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "fan_mode", ID_TEXT_8, 7, 186, 109, 20, 0, 0x64, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
extern char fbuf[200];
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Temperature:'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hItem, GUI_FONT_16_1);
    //
    // Initialization of 'temperature_value'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetText(hItem, "-999");
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    //
    // Initialization of 'slider_value'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetText(hItem, "desired_temp");
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    //
    // Initialization of 'Desired Temperature:'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetFont(hItem, GUI_FONT_16_1);
    //
    // Initialization of 'Radio'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_RADIO_0);
    RADIO_SetText(hItem, "Auto", 0);
    RADIO_SetText(hItem, "Manual", 1);
    //
    // Initialization of 'Fan:'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetFont(hItem, GUI_FONT_16_1);
    //
    // Initialization of 'fan_state'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
    TEXT_SetText(hItem, "OFF");
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    //
    // Initialization of 'Fan On'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, GUI_FONT_16_1);
    //
    // Initialization of 'Fan Off'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetFont(hItem, GUI_FONT_16_1);
    //
    // Initialization of 'info_message'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
    TEXT_SetFont(hItem, GUI_FONT_16_1);
    //
    // Initialization of 'Current Fanmode:'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
    TEXT_SetFont(hItem, GUI_FONT_16_1);
    //
    // Initialization of 'fan_mode'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
    TEXT_SetText(hItem, "Auto");
    TEXT_SetFont(hItem, GUI_FONT_20_1);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_SLIDER_0: // Notifications sent by 'Slider'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
					hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_0);
					uint8_t value = SLIDER_GetValue(hItem);
					hItem =  WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
					setTextInt(hItem, value);
					state.desired = value;
					
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_RADIO_0: // Notifications sent by 'Radio'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				hItem = WM_GetDialogItem(pMsg->hWin, ID_RADIO_0);
				uint8_t value = RADIO_GetValue(hItem);
				if(value == 0){
					hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
					TEXT_SetText(hItem, "Auto");
					state.fan_mode = 0;
					setSuccessMessage();
				}else if(value == 1){
					hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
					TEXT_SetText(hItem, "Manual");
					state.fan_mode = 1;
					setSuccessMessage();
				}
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_0: // Notifications sent by 'Fan On'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				if(state.fan_mode == 1){ // on manual
					setFanState(1); // ON
					setSuccessMessage();
				}else {
					setInfoMessage("Can't do that, fan in auto");
				}
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Fan Off'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
				if(state.fan_mode == 1){ // on manual
					setFanState(0); // OFF
					setSuccessMessage();
				}else {
					setInfoMessage("Can't do that, fan in auto");
				}
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateTemperatuur
*/
WM_HWIN CreateTemperatuur(void);
WM_HWIN CreateTemperatuur(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
